// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_by_user_feed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const delFeedFollow = `-- name: DelFeedFollow :exec
DELETE FROM feed_follows WHERE user_id=$1 AND feed_id=$2
`

type DelFeedFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DelFeedFollow(ctx context.Context, arg DelFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, delFeedFollow, arg.UserID, arg.FeedID)
	return err
}
