// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users_by_id.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserName = `-- name: GetUserName :one
SELECT name FROM users WHERE id=$1
`

func (q *Queries) GetUserName(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserName, id)
	var name sql.NullString
	err := row.Scan(&name)
	return name, err
}
